# Generated by Django 4.2.23 on 2025-07-13 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dc1Device',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(default='0000', max_length=8)),
                ('I', models.IntegerField(default=0)),
                ('V', models.IntegerField(default=0)),
                ('P', models.IntegerField(default=0)),
                ('update_time', models.BigIntegerField(default=0)),
                ('online', models.BooleanField(default=False)),
                ('power_start_time', models.BigIntegerField(default=0)),
                ('total_power', models.BigIntegerField(default=0)),
                ('names', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('command', models.CharField(max_length=8)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_server.dc1device')),
            ],
        ),
    ]
